# **Pandas Implementation Sheet - Student Data**

In [1]:
#Importing
import pandas as pd

In [2]:
# Dataset
data = {
    "Student_ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Aman","Riya","Rahul","Neha","Arjun","Priya","Karan","Sneha","Vikas","Anjali"],
    "Age": [18,19,18,20,19,21,20,18,19,21],
    "Department": ["CS","IT","CS","ECE","IT","CS","ECE","IT","CS","ECE"],
    "Math": [85,72,95,68,88,76,91,64,83,97],
    "Physics": [78,85,91,74,82,69,87,71,79,94],
    "Chemistry": [92,79,89,70,85,80,93,68,88,96],
    "Attendance": [92,85,96,72,88,79,94,68,86,97],
    "Final_Score": [88,81,94,72,90,75,89,70,84,98]
}

df = pd.DataFrame(data)
df

,Student_ID,Name,Age,Department,Math,Physics,Chemistry,Attendance,Final_Score
0,101,Aman,18,CS,85,78,92,92,88
1,102,Riya,19,IT,72,85,79,85,81
2,103,Rahul,18,CS,95,91,89,96,94
3,104,Neha,20,ECE,68,74,70,72,72
4,105,Arjun,19,IT,88,82,85,88,90
5,106,Priya,21,CS,76,69,80,79,75
6,107,Karan,20,ECE,91,87,93,94,89
7,108,Sneha,18,IT,64,71,68,68,70
8,109,Vikas,19,CS,83,79,88,86,84
9,110,Anjali,21,ECE,97,94,96,97,98

**Level 1 — Pandas Basics**

Q1 Display the first 5 rows.

Q2 Display the last 3 rows.

Q3 Find the number of rows and columns.

Q4 Display all column names.

Q5 Display the data types of every column.

Q6 Display basic information about the DataFrame.

Q7 Generate statistical summary of numerical columns.

Q8 Select only the Name column.

Q9 Select Name, Department, and Final_Score.

Q10 Select the first student using .iloc.

Q11 Select rows 2 to 5 using .iloc.

Q12 Select the Name of the student at index 4 using .loc.

Q13 Select students from index 3 to 7 using .loc.

Q14 Select only Math, Physics, and Chemistry.

Q15 Find the shape of the selected subject DataFrame.

In [3]:
df.head()

,Student_ID,Name,Age,Department,Math,Physics,Chemistry,Attendance,Final_Score
0,101,Aman,18,CS,85,78,92,92,88
1,102,Riya,19,IT,72,85,79,85,81
2,103,Rahul,18,CS,95,91,89,96,94
3,104,Neha,20,ECE,68,74,70,72,72
4,105,Arjun,19,IT,88,82,85,88,90

In [4]:
df.tail(3)

,Student_ID,Name,Age,Department,Math,Physics,Chemistry,Attendance,Final_Score
7,108,Sneha,18,IT,64,71,68,68,70
8,109,Vikas,19,CS,83,79,88,86,84
9,110,Anjali,21,ECE,97,94,96,97,98

In [5]:
df.shape

(10, 9)

In [6]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Department', 'Math', 'Physics',
       'Chemistry', 'Attendance', 'Final_Score'],
      dtype='object')

In [7]:
df.dtypes

Student_ID      int64
Name           object
Age             int64
Department     object
Math            int64
Physics         int64
Chemistry       int64
Attendance      int64
Final_Score     int64
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_ID   10 non-null     int64
 1   Name         10 non-null     object
 2   Age          10 non-null     int64
 3   Department   10 non-null     object
 4   Math         10 non-null     int64
 5   Physics      10 non-null     int64
 6   Chemistry    10 non-null     int64
 7   Attendance   10 non-null     int64
 8   Final_Score  10 non-null     int64
dtypes: int64(7), object(2)
memory usage: 852.0+ bytes

In [9]:
df.describe()

,Student_ID,Age,Math,Physics,Chemistry,Attendance,Final_Score
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,105.50000,19.300000,81.900000,81.000000,84.000000,85.700000,84.100000
std,3.02765,1.159502,11.435325,8.353309,9.568467,9.967168,9.445163
min,101.00000,18.000000,64.000000,69.000000,68.000000,68.000000,70.000000
25%,103.25000,18.250000,73.000000,75.000000,79.250000,80.500000,76.500000
50%,105.50000,19.000000,84.000000,80.500000,86.500000,87.000000,86.000000
75%,107.75000,20.000000,90.250000,86.500000,91.250000,93.500000,89.750000
max,110.00000,21.000000,97.000000,94.000000,96.000000,97.000000,98.000000

In [12]:
df["Name"]

0      Aman
1      Riya
2     Rahul
3      Neha
4     Arjun
5     Priya
6     Karan
7     Sneha
8     Vikas
9    Anjali
Name: Name, dtype: object

In [18]:
df[["Name","Department","Final_Score"]]

     Name Department  Final_Score
0    Aman         CS           88
1    Riya         IT           81
2   Rahul         CS           94
3    Neha        ECE           72
4   Arjun         IT           90
5   Priya         CS           75
6   Karan        ECE           89
7   Sneha         IT           70
8   Vikas         CS           84
9  Anjali        ECE           98

In [23]:
df.iloc[0]

Student_ID      101
Name           Aman
Age              18
Department       CS
Math             85
Physics          78
Chemistry        92
Attendance       92
Final_Score      88
Name: 0, dtype: object

In [24]:
df.iloc[2:6]

,Student_ID,Name,Age,Department,Math,Physics,Chemistry,Attendance,Final_Score
2,103,Rahul,18,CS,95,91,89,96,94
3,104,Neha,20,ECE,68,74,70,72,72
4,105,Arjun,19,IT,88,82,85,88,90
5,106,Priya,21,CS,76,69,80,79,75

In [28]:
df.loc[4]

Student_ID       105
Name           Arjun
Age               19
Department        IT
Math              88
Physics           82
Chemistry         85
Attendance        88
Final_Score       90
Name: 4, dtype: object

In [30]:
df.loc[3:7]

,Student_ID,Name,Age,Department,Math,Physics,Chemistry,Attendance,Final_Score
3,104,Neha,20,ECE,68,74,70,72,72
4,105,Arjun,19,IT,88,82,85,88,90
5,106,Priya,21,CS,76,69,80,79,75
6,107,Karan,20,ECE,91,87,93,94,89
7,108,Sneha,18,IT,64,71,68,68,70

In [31]:
df[['Math','Physics','Chemistry']]

   Math  Physics  Chemistry
0    85       78         92
1    72       85         79
2    95       91         89
3    68       74         70
4    88       82         85
5    76       69         80
6    91       87         93
7    64       71         68
8    83       79         88
9    97       94         96

In [32]:
df[['Math','Physics','Chemistry']].shape

(10, 3)

**Level 2 — Statistics & Selection**

Q16 Find the average Math score.

Q17 Find the average Physics score.

Q18 Find the average Chemistry score.

Q19 Find the average Final Score.

Q20 Find the highest Final Score.

Q21 Find the lowest Final Score.

Q22 Find the median Final Score.

Q23 Find the standard deviation of Final Score.

Q24 Find the average score across Math, Physics, and Chemistry.

Q25 Find the average subject score for each student.

In [38]:
df.Math.mean()

np.float64(81.9)

In [37]:
df.Physics.mean()

np.float64(81.0)

In [40]:
df.Chemistry.mean()

np.float64(84.0)

In [47]:
df.Final_Score.mean()

np.float64(84.1)

In [43]:
df.Final_Score.max()

98

In [44]:
df.Final_Score.min()

70

In [45]:
df.Final_Score.median()

86.0

In [48]:
df.Final_Score.std()

9.445163371329853

In [49]:
df[['Math','Physics','Chemistry']].mean()

Math         81.9
Physics      81.0
Chemistry    84.0
dtype: float64

In [50]:
df["Average_Subject_Score"] = df[["Math", "Physics", "Chemistry"]].mean(axis=1)
df[["Name", "Average_Subject_Score"]]

     Name  Average_Subject_Score
0    Aman              85.000000
1    Riya              78.666667
2   Rahul              91.666667
3    Neha              70.666667
4   Arjun              85.000000
5   Priya              75.000000
6   Karan              90.333333
7   Sneha              67.666667
8   Vikas              83.333333
9  Anjali              95.666667

**Level 3 — Filtering**

Q26 Find all students whose Math score is greater than 80.

Q27 Find all students whose Final Score is greater than 90.

Q28 Find all students whose Attendance is below 80.

Q29 Find students whose Math score is between 70 and 90.

Q30 Find students from the CS department.

In [64]:
df[df['Math'] >= 80]

,Student_ID,Name,Age,Department,Math,Physics,Chemistry,Attendance,Final_Score,Average_Subject_Score
0,101,Aman,18,CS,85,78,92,92,88,85.000000
2,103,Rahul,18,CS,95,91,89,96,94,91.666667
4,105,Arjun,19,IT,88,82,85,88,90,85.000000
6,107,Karan,20,ECE,91,87,93,94,89,90.333333
8,109,Vikas,19,CS,83,79,88,86,84,83.333333
9,110,Anjali,21,ECE,97,94,96,97,98,95.666667

In [63]:
df[df['Final_Score'] >= 90]

,Student_ID,Name,Age,Department,Math,Physics,Chemistry,Attendance,Final_Score,Average_Subject_Score
2,103,Rahul,18,CS,95,91,89,96,94,91.666667
4,105,Arjun,19,IT,88,82,85,88,90,85.000000
9,110,Anjali,21,ECE,97,94,96,97,98,95.666667

In [62]:
df[df['Attendance'] <= 80]

,Student_ID,Name,Age,Department,Math,Physics,Chemistry,Attendance,Final_Score,Average_Subject_Score
3,104,Neha,20,ECE,68,74,70,72,72,70.666667
5,106,Priya,21,CS,76,69,80,79,75,75.000000
7,108,Sneha,18,IT,64,71,68,68,70,67.666667

In [61]:
df[(df["Math"] >= 70) & (df["Math"] <= 90)]

,Student_ID,Name,Age,Department,Math,Physics,Chemistry,Attendance,Final_Score,Average_Subject_Score
0,101,Aman,18,CS,85,78,92,92,88,85.000000
1,102,Riya,19,IT,72,85,79,85,81,78.666667
4,105,Arjun,19,IT,88,82,85,88,90,85.000000
5,106,Priya,21,CS,76,69,80,79,75,75.000000
8,109,Vikas,19,CS,83,79,88,86,84,83.333333

In [65]:
df[df["Department"] == "CS"]

,Student_ID,Name,Age,Department,Math,Physics,Chemistry,Attendance,Final_Score,Average_Subject_Score
0,101,Aman,18,CS,85,78,92,92,88,85.000000
2,103,Rahul,18,CS,95,91,89,96,94,91.666667
5,106,Priya,21,CS,76,69,80,79,75,75.000000
8,109,Vikas,19,CS,83,79,88,86,84,83.333333