# **Learn about Pandas**

In [1]:
import numpy as np
import pandas as pd

## Pandas Series
A series is a one dimentional labeled array capable of holding any datatype. The axis labels are collectivelly called the index.

In [2]:
labels = ['a','b','c']
myList = [10,20,30]
npArray = np.array([10,20,30])
dict = {'a':10,'b':20,'c':30}

In [3]:
# Creating Series
pd.Series(myList,index=labels)

a    10
b    20
c    30
dtype: int64

## Pandas DataFrame

In [4]:
# Data and Creating a Dataframe

data = {
    "name": ["Peter", "John", "Sam", "Sara", "Virat"],
    "age": [21, 24, 22, 27, 23],
    "score": [85, 92, 78, 95, 88],
    "city": ["Delhi", "Mumbai", "Pune", "Bangalore", "Mumbai"]
}

df = pd.DataFrame(data)

In [5]:
# First 5 rows of dataset

df.head()

    name  age  score       city
0  Peter   21     85      Delhi
1   John   24     92     Mumbai
2    Sam   22     78       Pune
3   Sara   27     95  Bangalore
4  Virat   23     88     Mumbai

In [6]:
# Shape of dataset
df.shape

(5, 4)

In [7]:
df.columns

Index(['name', 'age', 'score', 'city'], dtype='object')

In [8]:
# Selecting Columns

df[["name","score"]]

    name  score
0  Peter     85
1   John     92
2    Sam     78
3   Sara     95
4  Virat     88

In [9]:
# Creating new columns/features
df["Gender"] = ["M","M","M","F","M"]

# display
df

    name  age  score       city Gender
0  Peter   21     85      Delhi      M
1   John   24     92     Mumbai      M
2    Sam   22     78       Pune      M
3   Sara   27     95  Bangalore      F
4  Virat   23     88     Mumbai      M

In [10]:
# Removing columns
df.drop("Gender",axis=1)

    name  age  score       city
0  Peter   21     85      Delhi
1   John   24     92     Mumbai
2    Sam   22     78       Pune
3   Sara   27     95  Bangalore
4  Virat   23     88     Mumbai

In [11]:
# Students whose score is greater than 85
df[df["score"] > 85][["name"]]

    name
1   John
3   Sara
4  Virat

In [12]:
# Student with highest score
df[df["score"] == df["score"].max()][["name","score"]]

   name  score
3  Sara     95

In [13]:
# Calculate Average Score
df["score"].mean()

np.float64(87.6)

In [14]:
df[["score"]].mean()

score    87.6
dtype: float64

## Missing Data

In [15]:
# Data and Creating a Dataframe

data = {
    "name": ["Peter", "John", "Sam", "Sara", "Virat", "Rahul", "Anita", "David"],
    "age": [21, 24, None, 27, 23, None, 25, 22],
    "score": [85, None, 78, 95, None, 88, 91, None],
    "city": ["Delhi", "Mumbai", None, "Bangalore", "Mumbai", None, "Pune", "Delhi"]
}

df = pd.DataFrame(data)

print(df)

    name   age  score       city
0  Peter  21.0   85.0      Delhi
1   John  24.0    NaN     Mumbai
2    Sam   NaN   78.0       None
3   Sara  27.0   95.0  Bangalore
4  Virat  23.0    NaN     Mumbai
5  Rahul   NaN   88.0       None
6  Anita  25.0   91.0       Pune
7  David  22.0    NaN      Delhi

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      object
 1   age     6 non-null      float64
 2   score   5 non-null      float64
 3   city    6 non-null      object
dtypes: float64(2), object(2)
memory usage: 388.0+ bytes

In [17]:
df.isna().sum()

name     0
age      2
score    3
city     2
dtype: int64

In [18]:
# Find missing value in columns
df.isna().any()

name     False
age       True
score     True
city      True
dtype: bool

In [19]:
# Remove all the row with null values
# df.dropna()

In [20]:
# Filling the missing data
df.fillna(0)

    name   age  score       city
0  Peter  21.0   85.0      Delhi
1   John  24.0    0.0     Mumbai
2    Sam   0.0   78.0          0
3   Sara  27.0   95.0  Bangalore
4  Virat  23.0    0.0     Mumbai
5  Rahul   0.0   88.0          0
6  Anita  25.0   91.0       Pune
7  David  22.0    0.0      Delhi

In [21]:
# Fill age with mean
df["age"] = df["age"].fillna(df["age"].mean())

# Fill score with mean
df["score"] = df["score"].fillna(df["score"].mean())

# Fill city with mode
df["city"] = df["city"].fillna(df["city"].mode()[0])

print(df)

    name        age  score       city
0  Peter  21.000000   85.0      Delhi
1   John  24.000000   87.4     Mumbai
2    Sam  23.666667   78.0      Delhi
3   Sara  27.000000   95.0  Bangalore
4  Virat  23.000000   87.4     Mumbai
5  Rahul  23.666667   88.0      Delhi
6  Anita  25.000000   91.0       Pune
7  David  22.000000   87.4      Delhi

## Merging Joining Concatination

In [22]:
import pandas as pd

data1 = {
    "id": [1, 2, 3, 4],
    "name": ["Peter", "John", "Sam", "Sara"]
}

data2 = {
    "id": [1, 2, 3, 4],
    "score": [85, 92, 78, 95]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

df = pd.merge(df1, df2, on="id")

print(df)

   id   name  score
0   1  Peter     85
1   2   John     92
2   3    Sam     78
3   4   Sara     95

In [23]:
data1 = {
    "name": ["Peter", "John"],
    "score": [85, 92]
}

data2 = {
    "name": ["Sam", "Sara"],
    "score": [78, 95]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

df = pd.concat([df1, df2], ignore_index=True)

print(df)

    name  score
0  Peter     85
1   John     92
2    Sam     78
3   Sara     95

In [24]:
df1 = pd.DataFrame({
    "name": ["Peter", "John", "Sam"],
    "score": [85, 92, 78]
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    "city": ["Delhi", "Mumbai", "Pune"]
}, index=[1, 2, 3])

df = df1.join(df2)

print(df)

    name  score    city
1  Peter     85   Delhi
2   John     92  Mumbai
3    Sam     78    Pune

In [25]:
import pandas as pd

df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Peter", "John", "Sam"]
})

df2 = pd.DataFrame({
    "id": [2, 3, 4],
    "score": [92, 78, 95]
})

df = pd.merge(df1, df2, on="id", how="outer")

print(df)

   id   name  score
0   1  Peter    NaN
1   2   John   92.0
2   3    Sam   78.0
3   4    NaN   95.0

## GroupBy and Aggregation

In [26]:
import pandas as pd

data = {
    "name": ["Peter", "John", "Sam", "Sara", "Virat", "Rahul"],
    "city": ["Delhi", "Mumbai", "Delhi", "Mumbai", "Delhi", "Pune"],
    "score": [85, 92, 78, 95, 88, 75],
    "age": [21, 24, 22, 27, 23, 25]
}

df = pd.DataFrame(data)

In [27]:
df.groupby("city")

In [28]:
df.groupby("city")["score"].mean()

city
Delhi     83.666667
Mumbai    93.500000
Pune      75.000000
Name: score, dtype: float64

In [29]:
df.groupby("city")["score"].sum()

city
Delhi     251
Mumbai    187
Pune       75
Name: score, dtype: int64

In [30]:
df.groupby("city")["score"].count()

city
Delhi     3
Mumbai    2
Pune      1
Name: score, dtype: int64

In [31]:
df.groupby("city")["score"].agg(["mean", "sum", "min", "max", "count"])

             mean  sum  min  max  count
city
Delhi   83.666667  251   78   88      3
Mumbai  93.500000  187   92   95      2
Pune    75.000000   75   75   75      1

In [32]:
df.groupby("city").agg({
    "score": "mean",
    "age": "max"
})

            score  age
city
Delhi   83.666667   23
Mumbai  93.500000   27
Pune    75.000000   25

In [33]:
df.groupby(["city", "age"])["score"].mean()

city    age
Delhi   21     85.0
        22     78.0
        23     88.0
Mumbai  24     92.0
        27     95.0
Pune    25     75.0
Name: score, dtype: float64